name: Deploy Project to GitHub Pages Subdirectory

on:
  push:
    branches:
      - main # Or master, or whatever your main development branch is
  workflow_dispatch: # Allows manual triggering of the workflow

permissions:
  contents: write # Required to push to the gh-pages branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    # Concurrency setting to ensure only one deployment happens at a time per branch/ref
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Or your project's Node.js version
          cache: 'npm' # Cache npm dependencies

      - name: Install dependencies
        run: npm ci # Use 'ci' for cleaner installs in CI environments

      - name: Build project
        run: npm run build # This will use your webpack.config.js with the production publicPath
        env:
          NODE_ENV: production # Ensure production mode for Webpack

      - name: Deploy to jespirit.github.io repository
        uses: peaceiris/actions-gh-pages@v3 # Or check for latest v4.x.x
        with:
          # Use the PAT you stored as a secret
          personal_token: ${{ secrets.GH_PAT }}
          # The repository to deploy to (your main portfolio)
          external_repository: jespirit/jespirit.github.io
          # The branch in jespirit.github.io to deploy to
          publish_branch: main # Or master, or whatever branch your portfolio serves from
          # The directory in coin-counter that contains the built assets
          publish_dir: ./dist
          # The subdirectory within jespirit.github.io/main where files will be placed
          destination_dir: coin-counter
          # Optional: Set a custom committer name and email
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          # Optional: Custom commit message
          commit_message: 'Deploy: Update coin-counter from ${{ github.repository }}@${{ github.sha }}'
          # `keep_files: false` (default) within destination_dir means it will
          # clear the `coin-counter` directory on the target branch before adding new files.
          # This is usually what you want for a clean deployment of the sub-project.
          # If you set `keep_files: true`, it would try to preserve other files
          # in the target repo, but with `destination_dir` it mainly affects that dir.
          keep_files: false